:root{--bg:#070b14;--card:#111827;--card2:#18243a;--text:#f8fafc;--muted:#94a3b8;--line:#293750;--accent:#f59e0b;--green:#22c55e;--red:#ef4444}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -20%,#17243d 0,#070b14 48%);color:var(--text);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif;padding-bottom:86px}a{text-decoration:none;color:inherit}
.top{position:sticky;top:0;z-index:10;padding:14px 16px;background:rgba(7,11,20,.9);backdrop-filter:blur(16px);border-bottom:1px solid var(--line);display:flex;justify-content:space-between;align-items:center}.brand{font-size:21px;font-weight:850}.sub,.muted{color:var(--muted);font-size:13px}.back{color:var(--accent);font-size:13px;display:block;margin-bottom:4px}.iconbtn{font-size:20px}
main{max-width:760px;margin:auto;padding:12px 14px}.hero{padding:22px 4px 12px}.hero h1{font-size:29px;line-height:1.1;margin:12px 0 6px}.pill{display:inline-block;background:#3a2908;color:#fbbf24;border:1px solid #62480e;border-radius:999px;padding:5px 9px;font-size:11px}
.primary,button{display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:13px;padding:11px 14px;font-weight:800;cursor:pointer}.primary,button:not(.secondary):not(.danger){background:var(--accent);color:#111827}.primary.big{padding:14px 18px}.full{width:100%}.secondary{background:var(--card2);color:var(--text);border:1px solid var(--line)}.danger{background:var(--red);color:white}.row{display:flex;align-items:center;justify-content:space-between;gap:10px;flex-wrap:wrap}
.stats{display:grid;grid-template-columns:repeat(2,1fr);gap:9px;margin:8px 0}.stats>div{background:var(--card);border:1px solid var(--line);border-radius:16px;padding:13px}.stats span,.foodmini span{display:block;color:var(--muted);font-size:12px}.stats b{font-size:21px;display:inline-block;margin-top:4px}.card{background:rgba(17,24,39,.92);border:1px solid var(--line);border-radius:18px;padding:15px;margin:10px 0}.sectionhead{display:flex;justify-content:space-between;align-items:center}.sectionhead h2{margin:0;font-size:17px}.sectionhead a{color:var(--accent);font-size:12px}
.history .item,.listitem{padding:12px 0;border-bottom:1px solid var(--line)}.history .item:last-child,.listitem:last-child{border-bottom:0}.foodmini{display:grid;grid-template-columns:1fr 1fr;gap:10px}.foodmini>div{background:var(--card2);border-radius:12px;padding:11px}.foodmini b{display:block;margin-top:4px}
.tabs{display:flex;gap:7px;overflow:auto;padding:4px 0}.tabs button{min-width:58px}.stickycard{position:sticky;top:75px;z-index:4}.timer{background:var(--card2);border-radius:12px;padding:8px 11px;text-align:center}.timer span{font-size:10px;color:var(--muted);display:block}.timer b{font-size:16px}
.exercise{background:var(--card);border:1px solid var(--line);border-radius:18px;padding:15px;margin:10px 0}.exercise h3{margin:0 0 4px}.exercise .prev{background:#0c1422;border-radius:11px;padding:9px;margin:9px 0;font-size:12px}.setgrid{display:grid;grid-template-columns:30px 1fr 1fr;gap:7px;align-items:center;margin-top:8px}.setgrid span{color:var(--muted);font-size:11px}.setdone{outline:2px solid var(--green)}
label{display:block;color:var(--muted);font-size:12px;margin:12px 0}input,select{width:100%;margin-top:5px;background:#0b1323;color:var(--text);border:1px solid var(--line);border-radius:10px;padding:11px;font-size:15px}hr{border:0;border-top:1px solid var(--line);margin:18px 0}.grid2{display:grid;grid-template-columns:1fr 1fr;gap:8px}.hidden{display:none}.notice{background:var(--card2);padding:11px;border-radius:12px;color:var(--muted);font-size:12px}.chart{width:100%;height:210px;background:#0b1323;border-radius:14px;margin-top:10px}
nav{position:fixed;bottom:0;left:0;right:0;height:76px;background:rgba(12,18,31,.97);border-top:1px solid var(--line);display:flex;justify-content:center;z-index:20}nav a{flex:1;max-width:150px;text-align:center;color:var(--muted);padding:10px 3px;font-size:20px}nav a.active{color:var(--accent)}nav small{display:block;font-size:10px;margin-top:3px}
.toast{position:fixed;bottom:90px;left:50%;transform:translateX(-50%);background:white;color:#111827;padding:10px 15px;border-radius:12px;font-weight:800;z-index:50}
@media(min-width:650px){.stats{grid-template-columns:repeat(4,1fr)}.hero{display:flex;align-items:center;justify-content:space-between;gap:20px}}
