function initHome(){
document.getElementById('week').textContent=db.week;document.getElementById('weight').textContent=db.weight.length?db.weight[db.weight.length-1].w+' kg':'—';
document.getElementById('days').textContent=workouts();document.getElementById('prs').textContent=prCount();document.getElementById('volume').textContent=Math.round(allVolume()).toLocaleString('nl-NL')+' kg';
const next=db.lastWorkout==='A'?'B':db.lastWorkout==='B'?'C':'A';document.getElementById('next').textContent='Volgende training: Training '+next+' • '+PLAN[next].length+' oefeningen';
const f=db.food[today()]||{kcal:0,protein:0};document.getElementById('cal').textContent=f.kcal+' / '+db.settings.kcal;document.getElementById('protein').textContent=f.protein+' / '+db.settings.protein+' g';
const dates=[...new Set(db.logs.map(x=>x.date))].sort().reverse().slice(0,5);document.getElementById('history').innerHTML=dates.length?dates.map(d=>{const logs=db.logs.filter(x=>x.date===d);return `<div class="item"><div class="row"><b>${d}</b><span class="muted">${logs.length} oefeningen</span></div><div class="muted small">${[...new Set(logs.map(x=>x.name))].slice(0,3).join(' • ')}</div></div>`}).join(''):'<p class="muted">Nog geen trainingen. Tijd voor de eerste! 💪</p>';
}
function initTraining(){
let current=db.lastWorkout==='C'?'A':db.lastWorkout==='A'?'B':'C'; // next suggestion
let active=location.hash.replace('#','')||current;
if(!PLAN[active])active='A';
function render(){
document.getElementById('workoutTitle').textContent=active;document.getElementById('trainingSub').textContent='Week '+db.week+' • '+(db.week===7?'Deload':'Richtwaarde '+rir()+' RIR');
document.getElementById('tabs').innerHTML=['A','B','C'].map(k=>`<button class="${k===active?'':'secondary'}" onclick="setActive('${k}')">${k}</button>`).join('');
const items=PLAN[active].map((e,i)=>renderExercise(e,i)).join('');document.getElementById('exercises').innerHTML=items;
document.getElementById('exerciseCount').textContent=PLAN[active].length+' oefeningen';updateSession();
}
window.setActive=k=>{active=k;history.replaceState(null,'','#'+k);render()}
window.saveSet=(key,sets,name)=>{const w=+document.getElementById(key+'w').value||0,reps=[];for(let i=0;i<sets;i++)reps.push(+document.getElementById(key+'r'+i).value||0);if(!reps.some(Boolean)){toast('Vul eerst je reps in');return}const item={key,week:db.week,date:today(),name,weight:w,reps};const ix=db.logs.findIndex(x=>x.key===key&&x.week===db.week);if(ix>=0)db.logs[ix]=item;else db.logs.push(item);if(!db.history[name])db.history[name]=[];const h=db.history[name],hi=h.findIndex(x=>x.date===today()&&x.week===db.week);const hist={date:today(),week:db.week,weight:w,reps};if(hi>=0)h[hi]=hist;else h.push(hist);save();toast('Set opgeslagen ✓');render()};
window.startRest=sec=>{let t=sec,el=document.getElementById('timer');clearInterval(window.rest);const tick=()=>{el.textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');if(t<=0){clearInterval(window.rest);toast('Rust voorbij 🔥')}t--};tick();window.rest=setInterval(tick,1000)}
window.finishWorkout=()=>{const logs=db.logs.filter(x=>x.date===today()&&x.key.startsWith(active+'|'));if(!logs.length){toast('Sla eerst je oefeningen op');return}document.getElementById('exercises').classList.add('hidden');document.querySelector('.stickycard').classList.add('hidden');document.getElementById('finish').classList.remove('hidden');document.getElementById('summary').innerHTML=`<p><b>${logs.length}</b> oefeningen opgeslagen.</p><p class="muted">Lekker bezig. Je progressie staat nu in je historie.</p>`}
function renderExercise(e,i){const key=active+'|'+i,old=db.logs.find(x=>x.key===key&&x.week===db.week),sets=db.week===7?Math.max(1,Math.ceil(e[1]*.67)):e[1],last=lastExercise(e[0]),weight=old?.weight??suggestion(e[0],e[2]),prev=last?`${last.weight} kg — ${last.reps.join(' / ')}`:'Nog geen vorige training';return `<article class="exercise"><h3>${e[0]}</h3><div class="muted">${sets} sets • ${e[2]} reps</div><div class="prev">Vorige: <b>${prev}</b></div><div class="row"><input id="${key}w" type="number" step=".5" value="${weight}" style="max-width:130px"><span class="muted">Richtwaarde RIR ${rir()}</span></div><div class="setgrid">${Array.from({length:sets},(_,s)=>`<span>Set ${s+1}</span><input id="${key}r${s}" type="number" placeholder="reps" value="${old?.reps?.[s]??''}"><button class="secondary" onclick="startRest(90)">⏱️</button>`).join('')}</div><button class="primary full" style="margin-top:10px" onclick="saveSet('${key}',${sets},'${e[0].replace(/'/g,"\'")}')">Opslaan ✓</button></article>`}
function updateSession(){const logs=db.logs.filter(x=>x.date===today()&&x.key.startsWith(active+'|'));document.getElementById('sessionStats').textContent=logs.length+' oefeningen opgeslagen • '+Math.round(logs.reduce((s,x)=>s+x.weight*x.reps.reduce((a,b)=>a+b,0),0)).toLocaleString('nl-NL')+' kg'}
render()
}
function initProgress(){
const names=Object.keys(db.history).length?Object.keys(db.history):PLAN.A.concat(PLAN.B,PLAN.C).map(x=>x[0]).filter((v,i,a)=>a.indexOf(v)===i);
document.getElementById('totalWorkouts').textContent=workouts();document.getElementById('prCount').textContent=prCount();document.getElementById('totalSets').textContent=db.logs.reduce((s,x)=>s+x.reps.length,0);document.getElementById('totalVolume').textContent=Math.round(allVolume()).toLocaleString('nl-NL')+' kg';
document.getElementById('prsList').innerHTML=names.map(n=>{const h=db.history[n]||[];if(!h.length)return '';const best=Math.max(...h.flatMap(x=>x.reps));const heavy=Math.max(...h.map(x=>x.weight));return `<div class="listitem row"><span><b>${n}</b><br><span class="muted">Beste reps: ${best}</span></span><span class="pr">${heavy} kg</span></div>`}).join('');
const sel=document.getElementById('exerciseSelect');sel.innerHTML=names.map(n=>`<option>${n}</option>`).join('');sel.onchange=()=>drawExercise(sel.value);if(names.length)drawExercise(names[0]);
const dates=[...new Set(db.logs.map(x=>x.date))].sort().reverse();document.getElementById('historyList').innerHTML=dates.map(d=>`<div class="listitem row"><b>${d}</b><span class="muted">${db.logs.filter(x=>x.date===d).length} oefeningen</span></div>`).join('')||'<p class="muted">Nog geen historie.</p>';
}
function drawExercise(name){const c=document.getElementById('exerciseChart'),ctx=c.getContext('2d'),h=db.history[name]||[],w=c.clientWidth||500,height=210,dpr=devicePixelRatio||1;c.width=w*dpr;c.height=height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,height);if(h.length<2){ctx.fillStyle='#94a3b8';ctx.fillText('Log minimaal 2 trainingen voor een grafiek.',15,35);return}const vals=h.map(x=>x.weight),min=Math.min(...vals)-2,max=Math.max(...vals)+2;ctx.strokeStyle='#f59e0b';ctx.lineWidth=3;ctx.beginPath();vals.forEach((v,i)=>{const x=15+i*(w-30)/(vals.length-1),y=height-20-(v-min)/(max-min)*(height-45);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#94a3b8';ctx.font='12px system-ui';ctx.fillText(max.toFixed(1)+' kg',10,15);ctx.fillText(min.toFixed(1)+' kg',10,height-5)}
function initFood(){const f=db.food[today()]||{kcal:0,protein:0};document.getElementById('kcal').value=f.kcal;document.getElementById('prot').value=f.protein;document.getElementById('calNow').textContent=f.kcal;document.getElementById('proteinNow').textContent=f.protein+' g';document.getElementById('calGoal').textContent='/ '+db.settings.kcal;document.getElementById('proteinGoal').textContent='/ '+db.settings.protein+' g'}
function saveFoodPage(){db.food[today()]={kcal:+document.getElementById('kcal').value||0,protein:+document.getElementById('prot').value||0};save();toast('Voeding opgeslagen 🍗');initFood()}
function initSettings(){document.getElementById('goal').value=db.settings.goal;document.getElementById('goalKcal').value=db.settings.kcal;document.getElementById('goalProtein').value=db.settings.protein}
function saveSettingsPage(){db.settings={goal:document.getElementById('goal').value,kcal:+document.getElementById('goalKcal').value||2550,protein:+document.getElementById('goalProtein').value||140};save();toast('Instellingen opgeslagen')}
function importDataPage(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{localStorage.setItem(KEY,r.result);db=load();toast('Import gelukt');setTimeout(()=>location.reload(),500)}catch(err){toast('Ongeldig bestand')}};r.readAsText(f)}
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
