const KEY='ruben-muscle-v5';const LEGACY=['ruben-muscle-v4','ruben-muscle-v3-1'];
const PLAN={A:[['Leg press',3,'8–12'],['Chest press',3,'8–12'],['Seated row',3,'8–12'],['Leg extension',2,'10–15'],['Lat pulldown',2,'8–12'],['Cable lateral raise',2,'10–15'],['Biceps curl',2,'10–15'],['Ab crunch',2,'10–15']],B:[['Hack squat / pendulum squat',3,'8–12'],['Incline chest press',3,'8–12'],['Seated leg curl',3,'10–15'],['Shoulder press',2,'8–12'],['Seated row',2,'8–12'],['Peck deck',2,'10–15'],['Triceps pushdown',2,'10–15'],['Leg abduction',2,'12–15'],['Calf raise',2,'10–15']],C:[['Leg press',3,'10–15'],['Lat pulldown',3,'8–12'],['Chest press',3,'8–12'],['Seated leg curl',3,'10–15'],['Rear delt machine',2,'10–15'],['Cable lateral raise',2,'10–15'],['Biceps curl',2,'10–15'],['Triceps pushdown',2,'10–15'],['Leg adduction',2,'12–15']]};
const DEFAULTS={'Chest press':30,'Peck deck':45,'Shoulder press':32.5,'Seated row':57,'Triceps pushdown':60,'Biceps curl':35,'Ab crunch':30};
const BASE={week:1,completedWorkouts:0,lastWorkout:'A',weight:[],logs:[],history:{},food:{},settings:{goal:'Spiermassa',kcal:2550,protein:140},sets:[],sessions:[],recipesOffset:0,customExercises:[]};
function migrate(x){if(!x)return structuredClone(BASE);const out={...BASE,...x,settings:{...BASE.settings,...(x.settings||{})},sets:x.sets||[],sessions:x.sessions||[],customExercises:x.customExercises||[]};if(!out.sets.length&&Array.isArray(x.logs)){x.logs.forEach(l=>{(l.reps||[]).forEach((r,i)=>{if(r)out.sets.push({date:l.date,week:l.week,workout:(l.key||'A|').split('|')[0],exercise:l.name,set:i+1,weight:l.weight,reps:r,rir:null})})})}return out}
function load(){try{let raw=localStorage.getItem(KEY);if(!raw)for(const k of LEGACY){raw=localStorage.getItem(k);if(raw)break}return migrate(JSON.parse(raw||'null'))}catch(e){return structuredClone(BASE)}}let db=load();
function save(){localStorage.setItem(KEY,JSON.stringify(db))}function dateKey(d=new Date()){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}function today(){return dateKey()}function toast(t){let e=document.querySelector('.toast');if(!e){e=document.createElement('div');e.className='toast';e.style.cssText='position:fixed;left:50%;bottom:92px;transform:translateX(-50%);z-index:99;background:#f8fafc;color:#0b1321;padding:12px 16px;border-radius:14px;font-weight:900;box-shadow:0 12px 35px #0008';document.body.appendChild(e)}e.textContent=t;clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>e.remove(),1900)}
function topRange(r){return +(String(r).split('–')[1]||12)}function lowRange(r){return +(String(r).split('–')[0]||8)}function exerciseSets(name){return db.sets.filter(x=>x.exercise===name).sort((a,b)=>a.date.localeCompare(b.date))}function lastExercise(name){const h=exerciseSets(name);if(!h.length)return null;const dates=[...new Set(h.map(x=>x.date))];const d=dates[dates.length-1];return {date:d,sets:h.filter(x=>x.date===d)}}
function advice(name,range){const last=lastExercise(name),lo=lowRange(range),hi=topRange(range);if(!last)return {weight:DEFAULTS[name]||'',target:lo,reason:'Eerste keer? Start rustig en kies een gewicht waarmee je de techniek goed houdt.'};const max=Math.max(...last.sets.map(x=>x.reps||0)),avg=Math.round(last.sets.reduce((s,x)=>s+x.reps,0)/last.sets.length);let weight=Math.max(...last.sets.map(x=>x.weight||0)),target=Math.min(hi,Math.max(lo,avg+1)),reason=`Vorige training: ${last.sets.map(x=>x.reps).join(' / ')} reps.`;if(max>=hi&&last.sets.length>0&&last.sets.every(x=>x.reps>=hi)){weight=+(weight+2.5).toFixed(1);target=lo;reason='Alle sets aan de bovenkant van de range. Gewicht iets verhogen en opnieuw opbouwen.'}else if(max<lo){target=lo;reason='Je zat onder de range. Houd het gewicht en probeer de ondergrens te halen.'}return {weight,target,reason,last}}
function rirDefault(){if(db.week<=3)return 3;if(db.week<=6)return 2;if(db.week===7)return 1;return 2}
function workouts(){return [...new Set(db.sets.map(x=>x.date))].length}function allVolume(){return db.sets.reduce((s,x)=>s+(x.weight||0)*(x.reps||0),0)}function prCount(){let n=0,seen={};db.sets.slice().sort((a,b)=>(a.date+a.set).localeCompare(b.date+b.set)).forEach(x=>{const best=(seen[x.exercise]||0),score=x.weight*(1+(x.reps||0)/30);if(score>best){n++;seen[x.exercise]=score}});return n}
function exportJSON(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='ruben-muscle-backup-v5.json';a.click()}function resetAll(){if(confirm('Alle trainingsgegevens wissen?')){localStorage.removeItem(KEY);LEGACY.forEach(k=>localStorage.removeItem(k));location.href='index.html'}}
